#!/bin/bash
#
#SBATCH --partition=long
#SBATCH --job-name=SLURM_Shotgun_Metagenomic_Pipeline
#SBATCH --error=SLURM_Shotgun_Metagenomic_Pipeline.err
#SBATCH --output=SLURM_Shotgun_Metagenomic_Pipeline.out
#SBATCH --ntasks=1
#SBATCH --time=150:00:00
#SBATCH --cpus-per-task=1
#SBATCH --mem-per-cpu=16000
#SBATCH --mail-type=FAIL
#SBATCH --mail-user=user@institution.edu

#Provide location for directory containing sequences, and directory to place pipeline output
SEQ_DIR=
OUT_DIR=

#Provide location of pipeline directory
PIPELINE_DIR=

#Launch pipeline script
${PIPELINE_DIR}/SLURM_Shotgun_Metagenomic_Pipeline.sh \
-i ${SEQ_DIR} \
-o ${OUT_DIR} \
-p "module load FastQC; module load R; PATH=$PATH:/home/${USER}/bbmap; source /home/${USER}/miniconda3/etc/profile.d/conda.sh; conda activate biobakery3" \
-r ${PIPELINE_DIR}/Reference_Files/GCA_000001405.15_GRCh38_full_plus_hs38d1_analysis_set \
-c ${PIPELINE_DIR}/Reference_Files/full_chocophlan.v296_201901b \
-u ${PIPELINE_DIR}/Reference_Files/uniref90_annotated_v201901b_full \
-t ${PIPELINE_DIR}/Reference_Files/mpa_v30_CHOCOPhlAn_201901_marker_info.txt.bz2 \
-f user@institution.edu
