#!/bin/bash
#
#SBATCH --partition=long
#SBATCH --job-name=Taxonomic_Functional_Profiling
#SBATCH --error=5.Taxonomic_Functional_Profiling.err
#SBATCH --output=5.Taxonomic_Functional_Profiling.out
#SBATCH --ntasks=1
#SBATCH --time=150:00:00
#SBATCH --cpus-per-task=1
#SBATCH --mem-per-cpu=8000
#SBATCH --mail-type=FAIL
#SBATCH --mail-user=wallenz@uab.edu

#Provide location of pipeline output directory
RESULTS_DIR=

#Provide location of pipeline directory
PIPELINE_DIR=

#Launch pipeline script
${PIPELINE_DIR}/SLURM_Shotgun_Metagenomic_Pipeline/5.Taxonomic_Functional_Profiling.sh \
-o $RESULTS_DIR \
-p "source /home/${USER}/miniconda3/etc/profile.d/conda.sh; conda activate biobakery3" \
-c ${PIPELINE_DIR}/Reference_Files/full_chocophlan.v296_201901 \
-u ${PIPELINE_DIR}/Reference_Files/uniref90_annotated_v201901 \
-t ${PIPELINE_DIR}/Reference_Files/mpa_v30_CHOCOPhlAn_201901_marker_info.txt.bz2 \
-f user@institution.edu
